package gameEngine.world.action.actions;

import utilities.Location;
import gameEngine.world.action.ActionList;
import gameEngine.world.unit.Unit;

/**
 * represents many move actions as a single one, used to move units when a list of
 * locations is generated by the pathfinder
 * @author Jack
 *
 */
public final class MoveList extends ActionList
{
	public MoveList(Unit u, Location[] l)
	{
		super("move");
		for(int i = 0; i < l.length; i++)
		{
			addActionToList(new Move(u, l[i].x, l[i].y));
		}
	}
	public void cancelAction(){} //overridden because move actions do not require canceling
}
